### ISSUE TITLE
Support Tracing

### ISSUE THREAD

**Issue by rceleste125** [Open-Credentialing-Initiative/OCI-Change-Requests#12]
# Steering: Proposal Summary 
`Used to propose a change or addition to Steering.`
`This is for the Steering work START approval step. Discuss the proposed work or change.`
#

The PDG Blueprint Chapter 5 includes optional usage of OCI credentials in TI Request and TI Response messages used to trace product ownership.  The current OCI artifacts were created with DSCSA PI Verification in mind.  Adjustments may need to be made to accommodate usage of OCI credentials for Tracing.

**This request is to:**

1. Determine the impact to OCI artifacts (ex: is the wallet required to log what type of transaction the credential is used for?). 
2. Adjust OCI artifacts (ex: Trace inclusive language,  create Trace solution conformance criteria)
3. Adjust OCI website and other messaging

# Steering: Publication Summary 
`Used to present completed work to Steering for approval to publish.`
`Discuss the work that was completed in reference to the above proposal.  Include any differences from the proposal and why.`
`use [GitHub Preview](https://htmlpreview.github.io/) to show the final state of documents along with pull requests (if needed).`
#

---

Detailed Description:

Consideration: If Trading Partners desire to differentiate whether a credential was used for Verification or Tracing.
---

Triage:
- [x] Is Issue appropriate for OCI Architecture
- [x]  Assign Size
- [x]  Assign Priority
- [x]  Assign Label (if needed)
- [x]  OCI affected Artifacts Identified
- [ ]  Assign Triage - Artifact Version Target (v x.x.x Milestone)
- [ ]  Assign Triage - Interop Profile Version Target (v x.x.x Milestone)
- [ ]  Create sub-project (if needed)
 
Affected Parties (help determine Sunrise/Sunset):
- [x] Trading Partners
- [ ] Issuers
- [x] Wallet Solutions
- [ ] PI Verification Solutions
- [x] TI Trace Solutions

**Affected OCI Artifact**
    
- [ ] Schema Document
- [ ] Identity Schema
- [ ] ATP Schema
- [ ] ATP-Equivalent Schema
- [ ] DSCSA Authority Schema
- [ ] Issuer Conformance Criteria
- [x] Wallet Conformance Criteria
- [ ] VRS Solution Conformance Criteria
- [x] Trace Solution Conformance Criteria
- [ ] Wallet API Specification
- [ ] Governance Document
- [ ] Conformance Program
- [ ] OCI Website
- [ ] Internal Process  

**Change Category (Guides Steering Review)**

   **- Steering/Industry Review**    
- [x] Business-Level (May affect business operations)
- [ ] OCI Governance, Policy or website feature

**- Steering/Industry Notification**
- [ ] Technical-Level (Does not affect business operations)
- [ ] OCI Internal Process or Infrastructure 

Communication
- [x] Website
- [x] Press Release
- [ ]  Newsletter
- [ ]  email:
- [ ]  Other:

**Comment by rceleste125** [comment]
**OPEN Questions regarding the use of credentials in Tracing**

1. Generalization of some specifications to accommodate Verification and Tracing
2. Specify that specifications support the Use Cases of PI Verification and Tracing
3. Call out what the common elements are for both Use Cases (supporting the ATP requirement for both Use Cases)
4. Elevate the Trust established by the Identity Credential
5. API changes 

> 5a. PI Verify Generate and Verify use the full PI (4 attributes), CorrID (UUID)
> 5b. Tracing uses GTIN/Sn, GTIN/Lot, NDC/Sn, NDC/Lot, CorrID (UUID)

6. Credential Presentation

> 6a. Use of Aud (Audience) property?

**Comment by bluesteens** [comment]
P&A call, 11/2: 
suggestion to create new CC similar to VRS CC
align with 2nd maturity level

**Comment by rceleste125** [comment]
![Image](https://github.com/Open-Credentialing-Initiative/OCI-Change-Requests/assets/40276798/12ed2cc8-5233-40ee-beaa-f797d9ce1e24)

**Comment by rceleste125** [comment]
Team to review draft document: https://docs.google.com/document/d/1tB-sabVPECBpfzPSCMWPuZ4M2spL-pv1FBWKETN2gFQ/edit

Approval discussion on 12/14/2023
