### ISSUE TITLE
ATP Credential change request

### ISSUE THREAD

**Issue by rceleste125** [Open-Credentialing-Initiative/OCI-Change-Requests#3]
### Tasks

- [x] Add Repackager and 3PL to Organization type
- [x] Fix syntax in Schema Document introduction.

affects 3 artifacts

- Wallet criteria
- issuer criteria
- VC schema documentation (scope to exclude schema validation idea)

**Comment by bluesteens** [comment]
**Triage:**

- [x] Is Issue appropriate for OCI Architecture
- [x] Assign **Size**
- [x] Assign **Priority**
- [x] Assign **Label** (if needed)
- [x] OCI affected Artifacts Identified
- [x] Assign **Triage - Artifact Version Target** (v x.x.x Milestone)
- [x] Assign **Triage - Interop Profile Version Target** (v x.x.x Milestone)
- [ ] Create sub-project (if needed)


**Affected Parties (help determine Sunrise/Sunset):**
    
- [ ] Trading Partners
- [x] Issuers 
- [x] Wallet Solutions
- [ ] PI Verification Solutions  


**Communication**
    
- [ ] Website
- [ ] Newsletter
- [ ] email:
- [ ] Other:

**Comment by rceleste125** [comment]
Per Steering Direction to complete.

**Comment by alexcolganLD** [comment]
Associated pull requests:
https://github.com/Open-Credentialing-Initiative/schemas/pull/5
https://github.com/Open-Credentialing-Initiative/Credential-Issuer-Conformance-Criteria/pull/7
https://github.com/Open-Credentialing-Initiative/Digital-Wallet-Conformance-Criteria/pull/27

https://github.com/Open-Credentialing-Initiative/schemas/pull/4

**Comment by rceleste125** [comment]
Schema Document v1.0.0 moves to v1.1.0
Issuer Conformance Criteria v2.0.0 moves to v2.1.0
Wallet Conformance Criteria v3.1.0 move to v3.2.0
Interoperability Profile v3.0.0 move to v3.1.0

**Comment by bluesteens** [comment]
we need to move the edits to DRAFT before merging @alexcolganLD
