### ISSUE TITLE
Consolidate Conformance Criteria Intros into Getting Started

### ISSUE THREAD

**Issue by rceleste125** [Open-Credentialing-Initiative/OCI-Change-Requests#7]
Each Conformance Criteria Document contains information in its Introduction section.  The proposal is to move this content to the Getting Started area and reference it in each Conformance Criteria Document. 

[tasklist]

### Tasks
- [x] Credential Issuer Conformance Criteria Intro edits
- [x] Wallet Conformance Criteria Intro edits
- [x] Getting Started edits

**Comment by bluesteens** [comment]
**Triage:**

- [x] Is Issue appropriate for OCI Architecture
- [ ] Create Steering-level Summary of request
- [x] Assign **Size**
- [x] Assign **Priority**
- [x] Assign **Label** (if needed)
- [x] OCI affected Artifacts Identified
- [ ] Assign **Triage - Artifact Version Target** (v x.x.x Milestone)
- [ ] Assign **Triage - Interop Profile Version Target** (v x.x.x Milestone)
- [ ] Create sub-project (if needed)


**Affected Parties (help determine Sunrise/Sunset):**
    
- [ ] Trading Partners
- [ ] Issuers 
- [ ] Wallet Solutions
- [ ] PI Verification Solutions  


**Affected OCI Artifact**
    
- [ ] Schema Document
- [ ] Identity Schema
- [ ] ATP Schema
- [x] Issuer Conformance Criteria
- [x] Wallet Conformance Criteria
- [x] VRS Solution Conformance Criteria
- [ ] Wallet API Specification
- [ ] Governance Document
- [ ] Conformance Program
- [ ] OCI Website
- [ ] Internal Process  
- [x] Getting Started

**Change Category (Guides Steering Review)**

   **- Steering/Industry Review**    
- [ ] Business-Level (May affect business operations)
- [ ] OCI Governance, Policy or website feature

**- Steering/Industry Notification**
- [x] Technical-Level (Do not affect business operations)
- [ ] OCI Internal Process or Infrastructure

**Comment by rceleste125** [comment]
Non-Normative Change.

**Comment by bluesteens** [comment]
'Getting started' edits were made a good while back but might need review following wallet/issuer criteria edits since then

**Comment by bluesteens** [comment]
'Getting started' updated

**Comment by bluesteens** [comment]
issuer criteria edits: https://github.com/Open-Credentialing-Initiative/Credential-Issuer-Conformance-Criteria/pull/13
wallet criteria edits: https://github.com/Open-Credentialing-Initiative/Digital-Wallet-Conformance-Criteria/pull/52

**Comment by bluesteens** [comment]
July, 27: to be released in Digital Wallet Criteria v3.3.0,  interop profile v3.2.0
